import pybullet as p
import pybullet_data
import time

physicsClient = p.connect(p.GUI)
p.setAdditionalSearchPath(pybullet_data.getDataPath())
#p.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)
# adding the force of gravity
p.setGravity(0,0,-9.8)
# adding a floor
planeId = p.loadURDF("plane.urdf")
# loading in the world stored in box.sdf generated by generate.py
p.loadSDF("world.sdf")
for i in range(100000):
    p.stepSimulation()
    time.sleep(1/60)
    print(i)
p.disconnect()
